// SPDX-License-Identifier: Apache-2.0
import type { Operation } from "../config/catalog";

export const CREATE_TWEET_FEATURES_KNOWN_GOOD = {
  "interactive_text_enabled": true,
  "longform_notetweets_inline_media_enabled": true,
  "longform_notetweets_rich_text_read_enabled": true,
  "longform_notetweets_consumption_enabled": true,
  "tweet_awards_web_tipping_enabled": false,
  "freedom_of_speech_not_reach_fetch_enabled": true,
  "standardized_nudges_misinfo": true,
  "tweet_with_visibility_results_prefer_gql_limited_actions_policy_enabled": true,
  "rweb_video_timestamps_enabled": true,
  "longform_notetweets_prompts_enabled": true,
  "creator_subscriptions_tweet_preview_api_enabled": true,
  "c9s_tweet_anatomy_moderator_badge_enabled": true,
  "articles_preview_enabled": true,
  "rweb_tipjar_consumption_enabled": true,
  "responsive_web_graphql_exclude_directive_enabled": true,
  "verified_phone_label_enabled": false,
  "responsive_web_graphql_skip_user_profile_image_extensions_enabled": false,
  "responsive_web_graphql_timeline_navigation_enabled": true,
  "responsive_web_enhance_cards_enabled": false
};

export const DEFAULT_FEATURES: Record<string, boolean | number | string> = {
  "all_enabled": true,
  "articles_preview_enabled": true,
  "articles_rest_api_enabled": true,
  "blue_business_multi_affiliates_ui_enabled": true,
  "blue_longer_video_enabled": true,
  "branded_features_is_branded_likes_on_tweet_content_enabled": false,
  "c9s_enabled": true,
  "c9s_tweet_anatomy_moderator_badge_enabled": true,
  "co_timeline_topic_filter_enabled": true,
  "communities_non_member_reply_enabled": true,
  "communities_web_enable_tweet_community_results_fetch": true,
  "content_disclosure_ai_generated_indicator_enabled": true,
  "content_disclosure_indicator_enabled": true,
  "creator_subscriptions_tweet_preview_api_enabled": true,
  "disallowed_reply_controls_callout_enabled": false,
  "dm_conversations_nsfw_media_filter_enabled": false,
  "dont_mention_me_view_api_enabled": true,
  "freedom_of_speech_not_reach_fetch_enabled": true,
  "graphql_is_translatable_rweb_tweet_is_translatable_enabled": true,
  "gryphon_underground_enabled": false,
  "hidden_profile_subscriptions_enabled": true,
  "highlights_tweets_tab_ui_enabled": true,
  "is_enabled": true,
  "longform_notetweets_composition_without_claims_enabled": true,
  "longform_notetweets_consumption_enabled": true,
  "longform_notetweets_inline_media_enabled": true,
  "longform_notetweets_max_weighted_character_length": false,
  "longform_notetweets_rich_composition_enabled": true,
  "longform_notetweets_rich_text_read_enabled": true,
  "longform_notetweets_tweet_storm_enabled": true,
  "optimized_sru_parameters_enabled": true,
  "post_ctas_fetch_enabled": true,
  "premium_content_api_read_enabled": true,
  "profile_label_improvements_pcf_label_in_post_enabled": true,
  "profile_sort_enabled": true,
  "responsive_web_alt_text_nudges_enabled": true,
  "responsive_web_api_transition_enabled": true,
  "responsive_web_birdwatch_consumption_enabled": true,
  "responsive_web_birdwatch_pivots_enabled": true,
  "responsive_web_castle_client_event_enabled": false,
  "responsive_web_castle_public_key": false,
  "responsive_web_castle_sdk_enabled": false,
  "responsive_web_composer_configurable_video_player_enabled": true,
  "responsive_web_cookie_compliance_1st_party_killswitch_list": false,
  "responsive_web_cookie_compliance_gingersnap_enabled": false,
  "responsive_web_cookie_consent_signal_enabled": false,
  "responsive_web_edit_tweet_api_enabled": true,
  "responsive_web_edit_tweet_enabled": true,
  "responsive_web_edit_tweet_perspective_enabled": false,
  "responsive_web_enhance_cards_enabled": false,
  "responsive_web_extension_compatibility_hide": false,
  "responsive_web_extension_compatibility_override_param": false,
  "responsive_web_fetch_hashflags_on_boot": true,
  "responsive_web_graphql_feedback": false,
  "responsive_web_graphql_skip_user_profile_image_extensions_enabled": false,
  "responsive_web_graphql_timeline_navigation_enabled": true,
  "responsive_web_grok_analysis_button_from_backend": true,
  "responsive_web_grok_analyze_button_fetch_trends_enabled": true,
  "responsive_web_grok_analyze_post_followups_enabled": true,
  "responsive_web_grok_annotations_enabled": true,
  "responsive_web_grok_article_summary_enabled": true,
  "responsive_web_grok_bio_auto_translation_in_followers_enabled": false,
  "responsive_web_grok_bio_auto_translation_in_search_is_enabled": false,
  "responsive_web_grok_bio_auto_translation_is_enabled": false,
  "responsive_web_grok_community_note_auto_translation_is_enabled": false,
  "responsive_web_grok_image_annotation_enabled": true,
  "responsive_web_grok_imagine_annotation_enabled": true,
  "responsive_web_grok_link_edit_image_to_grok_com_enabled": false,
  "responsive_web_grok_media_attribution_focal_post_force_show": false,
  "responsive_web_grok_media_attribution_imagine_force_show": false,
  "responsive_web_grok_media_attribution_route_to_imagine_composer": false,
  "responsive_web_grok_share_attachment_enabled": true,
  "responsive_web_grok_show_grok_translated_post": false,
  "responsive_web_grok_tweet_media_detail_edit_image_button_enabled": false,
  "responsive_web_grok_tweet_media_edit_image_button_enabled": false,
  "responsive_web_hevc_upload_preview_enabled": false,
  "responsive_web_jetfuel_frame": false,
  "responsive_web_locale_context_direction_enabled": true,
  "responsive_web_logged_out_ios_webview_redirect_enabled": false,
  "responsive_web_media_upload_appendmulti_enabled": true,
  "responsive_web_media_upload_appendmulti_max_concurrent_requests": false,
  "responsive_web_media_upload_appendmulti_max_request_bytes": false,
  "responsive_web_media_upload_appendmulti_max_segment_bytes": false,
  "responsive_web_media_upload_appendmulti_min_file_bytes": false,
  "responsive_web_media_upload_appendmulti_min_segment_bytes": false,
  "responsive_web_media_upload_appendmulti_pre_read_blob": false,
  "responsive_web_media_upload_appendmulti_target_wire_send_time_ms": false,
  "responsive_web_media_upload_host": false,
  "responsive_web_media_upload_limit_2g": false,
  "responsive_web_media_upload_limit_3g": false,
  "responsive_web_media_upload_limit_slow_2g": false,
  "responsive_web_media_upload_md5_hashing_enabled": true,
  "responsive_web_media_upload_metrics_enabled": false,
  "responsive_web_media_upload_target_jpg_pixels_per_byte": false,
  "responsive_web_ocf_reportflow_appeals_enabled": true,
  "responsive_web_ocf_reportflow_dms_enabled": true,
  "responsive_web_ocf_reportflow_lists_enabled": true,
  "responsive_web_ocf_reportflow_profiles_enabled": true,
  "responsive_web_ocf_reportflow_spaces_enabled": true,
  "responsive_web_ocf_reportflow_suspension_appeals_enabled": true,
  "responsive_web_ocf_reportflow_testers": false,
  "responsive_web_ocf_reportflow_tweets_enabled": true,
  "responsive_web_ocf_reportflow_user_label_appeals_enabled": true,
  "responsive_web_profile_redirect_enabled": true,
  "responsive_web_redux_use_fragment_enabled": false,
  "responsive_web_send_cookies_metadata_enabled": false,
  "responsive_web_service_worker_update_toast_interval_hours": false,
  "responsive_web_spud_enabled": false,
  "responsive_web_timeline_relay_lists_management_enabled": true,
  "responsive_web_timezone_header_enabled": false,
  "responsive_web_tracer_global_trace_sample_rate": false,
  "responsive_web_twitter_article_notes_tab_enabled": true,
  "responsive_web_twitter_article_plain_text_enabled": true,
  "responsive_web_twitter_article_seed_tweet_detail_enabled": true,
  "responsive_web_twitter_article_tweet_consumption_enabled": true,
  "responsive_web_x_translation_enabled": true,
  "rweb_cashtags_composer_attachment_enabled": true,
  "rweb_cashtags_enabled": true,
  "rweb_client_transaction_id_enabled": false,
  "rweb_conf_only_enabled": false,
  "rweb_conversational_replies_downvote_enabled": false,
  "rweb_debugger_enabled": false,
  "rweb_home_jot_migrate_enabled": false,
  "rweb_home_ranked_following_enabled": true,
  "rweb_home_uas_enabled": true,
  "rweb_media_carousel_enabled": true,
  "rweb_media_multi_requests_default_pool_size": false,
  "rweb_media_multi_requests_enabled": true,
  "rweb_search_media_enabled": true,
  "rweb_session_binding_enabled": false,
  "rweb_tipjar_consumption_enabled": true,
  "rweb_video_screen_enabled": true,
  "subscriptions_blue_verified_edit_profile_error_message_enabled": false,
  "subscriptions_upsells_api_enabled": true,
  "subscriptions_verification_info_is_identity_verified_enabled": true,
  "subscriptions_verification_info_verified_since_enabled": true,
  "super_follow_exclusive_tweet_creation_api_enabled": false,
  "toxic_reply_filter_inline_callout_enabled": false,
  "tweet_limited_actions_config_dpa_enabled": false,
  "tweet_limited_actions_config_enabled": true,
  "tweet_with_visibility_results_all_gql_limited_actions_enabled": false,
  "tweet_with_visibility_results_partial_gql_limited_actions_enabled": true,
  "tweet_with_visibility_results_prefer_gql_limited_actions_policy_enabled": true,
  "verified_phone_label_enabled": false,
  "video_attribution_display_over_video_cards_enabled": false,
  "view_counts_everywhere_api_enabled": true,
  "view_counts_public_visibility_enabled": true,
  "voice_consumption_enabled": false
};

/** Build the feature-flag subset for a given operation. */
export function featuresFor(op: Operation): Record<string, boolean | number | string> {
  if (op.featureSwitches.length === 0) {
    return { ...DEFAULT_FEATURES };
  }

  const out: Record<string, boolean | number | string> = {};
  for (const flag of op.featureSwitches) {
    const val = DEFAULT_FEATURES[flag];
    out[flag] = val !== undefined ? val : true;
  }
  return out;
}
